[PRMT-1471] Carried over gp2gp-adaptor codebase to initialise worker

diff --git a/tasks b/tasks
--- a/tasks
+++ b/tasks
@@ -7,7 +7,7 @@ set -Eeo pipefail
 ###########################
 
 AWS_DEFAULT_REGION=eu-west-2
-IMAGE_REPO_NAME=deductions/gp2gp-adaptor
+IMAGE_REPO_NAME=deductions/gp2gp-worker
 export NHS_SERVICE=gp2gp-worker
 
 ####################################
@@ -43,12 +43,22 @@ function configure_local_envs {
 }
 
 function get_latest_commit_hash {
-  export COMMIT_HASH=$(git rev-parse HEAD | cut -c 1-7)
+  export COMMIT_HASH=$(git rev-parse HEAD | cut -c 1-8)
 }
 
 function get_aws_account_id {
     AWS_ACCOUNT_ID=$(dojo -c Dojofile-infra "aws sts get-caller-identity | jq -r .Account")
- }
+}
+
+function get_aws_ssm_secret {
+ secret_id=$1
+ json=$(dojo -c Dojofile-infra "aws ssm get-parameter --with-decryption --region $AWS_DEFAULT_REGION --name $secret_id | jq -r '.Parameter.Value'")
+ if [ $? != 0 ]; then
+   >&2 echo "Failed to obtain AWS secret from SSM: $secret_id"
+   exit 5
+ fi
+ echo $json
+}
 
 #######################
 # Terraform Functions #
@@ -58,7 +68,7 @@ function tf_plan {
   operation=$1
   cd terraform
 
-  COMMIT_HASH=$(git rev-parse HEAD | cut -c 1-7)
+  COMMIT_HASH=$(git rev-parse HEAD | cut -c 1-8)
 
   if [[ -z "${GO_DEPENDENCY_LABEL_APP}" ]]; then
     echo "Must set GO_DEPENDENCY_LABEL_APP"
@@ -87,12 +97,124 @@ function tf_apply {
   terraform output -json > tf-out.json
 }
 
+####################
+# Script Functions #
+####################
+
+function send_canary_update_message {
+  check_nhs_service
+  node scripts/send-canary-update.js $(npm outdated --parseable)
+}
+
+function configure_hangout_webhook {
+  export GOOGLE_CHAT_CANARY_WEBHOOK=$(get_aws_ssm_secret "/repo/prod/user-input/gocd-google-chat-canary-webhook")
+  if [ -z "${GOOGLE_CHAT_CANARY_WEBHOOK}" ]; then
+    echo "Unable to obtain GOOGLE_CHAT_CANARY_WEBHOOK from AWS"
+    exit 5
+  fi
+}
+
+############################
+# Docker Related Functions #
+############################
+
+function docker_login {
+  echo Logging in to Amazon ECR...
+  eval $(dojo -c Dojofile-infra "aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION")
+}
+
+function configure_docker_repository_uri {
+  docker_login
+  get_aws_account_id
+  export REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/$IMAGE_REPO_NAME
+}
+
+function build_docker_image {
+  echo Build started on `date`
+  get_latest_commit_hash
+  IMAGE_TAG=${COMMIT_HASH}
+  echo Building the Docker image...
+  docker build -t $REPOSITORY_URI:latest -t $REPOSITORY_URI:$IMAGE_TAG .
+  echo Build completed on `date`
+}
+
 ###########
 ## TASKS ##
 ###########
 
 command="$1"
 case "${command}" in
+  _dep)
+      npm install
+      npm audit
+      ;;
+  dep)
+      dojo "./tasks _dep"
+      ;;
+  _list_outdated)
+      npm install
+      npm outdated > outdated-dependencies.txt || send_canary_update_message
+      ;;
+  list_outdated)
+      configure_hangout_webhook
+      dojo "./tasks _list_outdated"
+      ;;
+  update_package_json)
+      dojo "npx npm-check-updates -u"
+      ;;
+  send_dead_canary_message)
+      check_nhs_service
+      configure_hangout_webhook
+      dojo "node scripts/send-canary-error.js"
+      ;;
+  _build)
+      rm -rf build/
+      npm install
+      npm run build
+      ;;
+  build)
+      dojo "./tasks _build"
+      ;;
+  _test_lint)
+      npm install
+      npm run lint
+      ;;
+  test_lint)
+      dojo "./tasks _test_lint"
+      ;;
+  _test_unit)
+      npm install
+      npm run test:unit
+      ;;
+  test_unit)
+      dojo "./tasks _test_unit"
+      ;;
+  _test_integration)
+      npm install
+      npm run test:integration
+      ;;
+  test_integration)
+      configure_local_envs
+      dojo -c Dojofile-itest "./tasks _test_integration"
+      ;;
+  _test_coverage)
+      npm install
+      npm run test:coverage
+      ;;
+  test_coverage)
+      configure_local_envs
+      dojo -c Dojofile-itest "./tasks _test_coverage"
+      ;;
+  build_docker_local)
+      configure_local_envs
+      build_docker_image
+      ;;
+  build_docker)
+      configure_docker_repository_uri
+      build_docker_image
+      echo "Pushing the Docker image... $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG"
+      docker push $REPOSITORY_URI
+      ;;
   tf)
       check_env
       dojo -c Dojofile-infra "bash"
